//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yabfasp.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yabfasp.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the post to publish.
        /// </summary>
        internal static string CouldNotFindPostToPublishException {
            get {
                return ResourceManager.GetString("CouldNotFindPostToPublishException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to update a post that was null.
        /// </summary>
        internal static string PostToUpdateNullException {
            get {
                return ResourceManager.GetString("PostToUpdateNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A BlogManager has not been set for this Yet Another Blog.
        /// </summary>
        internal static string ValidationErrorNoBlogManager {
            get {
                return ResourceManager.GetString("ValidationErrorNoBlogManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithPersistence(IUnitOfWork) was not called when building this Yet Another Blog.
        /// </summary>
        internal static string ValidationErrorNoPersistence {
            get {
                return ResourceManager.GetString("ValidationErrorNoPersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PostManager has not been set for this Yet Another Blog.
        /// </summary>
        internal static string ValidationErrorNoPostManager {
            get {
                return ResourceManager.GetString("ValidationErrorNoPostManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content has been provided for this Post.
        /// </summary>
        internal static string ValidationErrorPostNoContent {
            get {
                return ResourceManager.GetString("ValidationErrorPostNoContent", resourceCulture);
            }
        }
    }
}
